name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Push to Hugging Face
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://__token__:${HF_TOKEN}@huggingface.co/spaces/AdityaSreevatsaK/Utility-Shelf
          git push hf main --force
        env:
          HF_TOKEN: ${{ secrets.HF_UTILITY_SHELF_TOKEN }}
